//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.EMTModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EMTContainer : DbContext
    {
        public EMTContainer()
            : base("name=EMTContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_DY_YZK> t_DY_YZK { get; set; }
        public virtual DbSet<t_DY_YZKEntry1> t_DY_YZKEntry1 { get; set; }
        public virtual DbSet<t_DY_YZKEntry2> t_DY_YZKEntry2 { get; set; }
        public virtual DbSet<t_DY_WorkProcedure> t_DY_WorkProcedure { get; set; }
        public virtual DbSet<t_User> t_User { get; set; }
        public virtual DbSet<t_ICItem> t_ICItem { get; set; }
        public virtual DbSet<t_DY_AmountType> t_DY_AmountType { get; set; }
        public virtual DbSet<t_Organization> t_Organization { get; set; }
        public virtual DbSet<t_BOS200000121Entry2> t_BOS200000121Entry2 { get; set; }
        public virtual DbSet<t_BOS200000123Entry2> t_BOS200000123Entry2 { get; set; }
        public virtual DbSet<t_BOS200000124Entry2> t_BOS200000124Entry2 { get; set; }
        public virtual DbSet<t_SubMessage> t_SubMessage { get; set; }
        public virtual DbSet<ICClassCheckStatus200000127> ICClassCheckStatus200000127 { get; set; }
        public virtual DbSet<t_Department> t_Department { get; set; }
        public virtual DbSet<t_BOS200000128Entry2> t_BOS200000128Entry2 { get; set; }
        public virtual DbSet<t_BOS200000130Entry2> t_BOS200000130Entry2 { get; set; }
        public virtual DbSet<t_dy_workprocedureentry> t_dy_workprocedureentry { get; set; }
        public virtual DbSet<t_DY_ColorNo> t_DY_ColorNo { get; set; }
        public virtual DbSet<t_DY_ColorNoEntry> t_DY_ColorNoEntry { get; set; }
        public virtual DbSet<t_DY_ShaPi> t_DY_ShaPi { get; set; }
        public virtual DbSet<t_ICItemCore> t_ICItemCore { get; set; }
        public virtual DbSet<t_TempDSK> t_TempDSK { get; set; }
        public virtual DbSet<t_TempDSKEntry2> t_TempDSKEntry2 { get; set; }
        public virtual DbSet<t_DY_MonldingGYLC> t_DY_MonldingGYLC { get; set; }
        public virtual DbSet<t_BOS200000129Entry2> t_BOS200000129Entry2 { get; set; }
        public virtual DbSet<ICStockBill> ICStockBill { get; set; }
        public virtual DbSet<ICStockBillEntry> ICStockBillEntry { get; set; }
        public virtual DbSet<t_MeasureUnit> t_MeasureUnit { get; set; }
        public virtual DbSet<t_DY_RGStockBill> t_DY_RGStockBill { get; set; }
        public virtual DbSet<t_DY_RGStockBillEntry> t_DY_RGStockBillEntry { get; set; }
        public virtual DbSet<t_Emp> t_Emp { get; set; }
        public virtual DbSet<t_DY_GYLC> t_DY_GYLC { get; set; }
        public virtual DbSet<t_DY_GYLCEntry> t_DY_GYLCEntry { get; set; }
        public virtual DbSet<CustomWorkFlowEntrySet> CustomWorkFlowEntrySet { get; set; }
        public virtual DbSet<CustomWorkFlowSet> CustomWorkFlowSet { get; set; }
        public virtual DbSet<GYLCLogSet> GYLCLogSet { get; set; }
    }
}
