//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.EMTModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICClassCheckStatus200000127
    {
        public int FID { get; set; }
        public int FPage { get; set; }
        public int FBillID { get; set; }
        public int FBillEntryID { get; set; }
        public string FBillNo { get; set; }
        public int FBillEntryIndex { get; set; }
        public int FCurrentLevel { get; set; }
        public int FCheckMan1 { get; set; }
        public string FCheckIdea1 { get; set; }
        public Nullable<System.DateTime> FCheckDate1 { get; set; }
        public int FCheckMan2 { get; set; }
        public string FCheckIdea2 { get; set; }
        public Nullable<System.DateTime> FCheckDate2 { get; set; }
        public int FCheckMan3 { get; set; }
        public string FCheckIdea3 { get; set; }
        public Nullable<System.DateTime> FCheckDate3 { get; set; }
        public int FCheckMan4 { get; set; }
        public string FCheckIdea4 { get; set; }
        public Nullable<System.DateTime> FCheckDate4 { get; set; }
        public int FCheckMan5 { get; set; }
        public string FCheckIdea5 { get; set; }
        public Nullable<System.DateTime> FCheckDate5 { get; set; }
        public int FCheckMan6 { get; set; }
        public string FCheckIdea6 { get; set; }
        public Nullable<System.DateTime> FCheckDate6 { get; set; }
        public int FCheckMan7 { get; set; }
        public string FCheckIdea7 { get; set; }
        public Nullable<System.DateTime> FCheckDate7 { get; set; }
        public int FCheckMan8 { get; set; }
        public string FCheckIdea8 { get; set; }
        public Nullable<System.DateTime> FCheckDate8 { get; set; }
        public int FCheckMan9 { get; set; }
        public string FCheckIdea9 { get; set; }
        public Nullable<System.DateTime> FCheckDate9 { get; set; }
        public int FCheckMan10 { get; set; }
        public string FCheckIdea10 { get; set; }
        public Nullable<System.DateTime> FCheckDate10 { get; set; }
        public int FCheckMan11 { get; set; }
        public string FCheckIdea11 { get; set; }
        public Nullable<System.DateTime> FCheckDate11 { get; set; }
        public int FCheckMan12 { get; set; }
        public string FCheckIdea12 { get; set; }
        public Nullable<System.DateTime> FCheckDate12 { get; set; }
        public int FCheckMan13 { get; set; }
        public string FCheckIdea13 { get; set; }
        public Nullable<System.DateTime> FCheckDate13 { get; set; }
        public int FCheckMan14 { get; set; }
        public string FCheckIdea14 { get; set; }
        public Nullable<System.DateTime> FCheckDate14 { get; set; }
        public int FCheckMan15 { get; set; }
        public string FCheckIdea15 { get; set; }
        public Nullable<System.DateTime> FCheckDate15 { get; set; }
    }
}
