//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.EMTModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICStockBillEntry
    {
        public string FBrNo { get; set; }
        public int FInterID { get; set; }
        public int FEntryID { get; set; }
        public Nullable<int> FItemID { get; set; }
        public decimal FQtyMust { get; set; }
        public decimal FQty { get; set; }
        public decimal FPrice { get; set; }
        public string FBatchNo { get; set; }
        public decimal FAmount { get; set; }
        public string FNote { get; set; }
        public Nullable<int> FSCBillInterID { get; set; }
        public string FSCBillNo { get; set; }
        public int FUnitID { get; set; }
        public decimal FAuxPrice { get; set; }
        public decimal FAuxQty { get; set; }
        public decimal FAuxQtyMust { get; set; }
        public decimal FQtyActual { get; set; }
        public decimal FAuxQtyActual { get; set; }
        public decimal FPlanPrice { get; set; }
        public decimal FAuxPlanPrice { get; set; }
        public int FSourceEntryID { get; set; }
        public decimal FCommitQty { get; set; }
        public decimal FAuxCommitQty { get; set; }
        public Nullable<System.DateTime> FKFDate { get; set; }
        public int FKFPeriod { get; set; }
        public Nullable<int> FDCSPID { get; set; }
        public Nullable<int> FSCSPID { get; set; }
        public decimal FConsignPrice { get; set; }
        public decimal FConsignAmount { get; set; }
        public decimal FProcessCost { get; set; }
        public decimal FMaterialCost { get; set; }
        public decimal FTaxAmount { get; set; }
        public string FMapNumber { get; set; }
        public string FMapName { get; set; }
        public int FOrgBillEntryID { get; set; }
        public Nullable<int> FOperID { get; set; }
        public decimal FPlanAmount { get; set; }
        public decimal FProcessPrice { get; set; }
        public decimal FTaxRate { get; set; }
        public Nullable<int> FSnListID { get; set; }
        public decimal FAmtRef { get; set; }
        public int FAuxPropID { get; set; }
        public decimal FCost { get; set; }
        public decimal FPriceRef { get; set; }
        public decimal FAuxPriceRef { get; set; }
        public Nullable<System.DateTime> FFetchDate { get; set; }
        public decimal FQtyInvoice { get; set; }
        public decimal FQtyInvoiceBase { get; set; }
        public decimal FUnitCost { get; set; }
        public decimal FSecCoefficient { get; set; }
        public decimal FSecQty { get; set; }
        public decimal FSecCommitQty { get; set; }
        public int FSourceTranType { get; set; }
        public int FSourceInterId { get; set; }
        public string FSourceBillNo { get; set; }
        public int FContractInterID { get; set; }
        public int FContractEntryID { get; set; }
        public string FContractBillNo { get; set; }
        public string FICMOBillNo { get; set; }
        public int FICMOInterID { get; set; }
        public int FPPBomEntryID { get; set; }
        public int FOrderInterID { get; set; }
        public int FOrderEntryID { get; set; }
        public string FOrderBillNo { get; set; }
        public decimal FAllHookQTY { get; set; }
        public decimal FAllHookAmount { get; set; }
        public decimal FCurrentHookQTY { get; set; }
        public decimal FCurrentHookAmount { get; set; }
        public decimal FStdAllHookAmount { get; set; }
        public decimal FStdCurrentHookAmount { get; set; }
        public int FSCStockID { get; set; }
        public int FDCStockID { get; set; }
        public Nullable<System.DateTime> FPeriodDate { get; set; }
        public int FCostObjGroupID { get; set; }
        public int FCostOBJID { get; set; }
        public int FDetailID { get; set; }
        public decimal FMaterialCostPrice { get; set; }
        public int FReProduceType { get; set; }
        public int FBomInterID { get; set; }
        public decimal FDiscountRate { get; set; }
        public decimal FDiscountAmount { get; set; }
        public int FSepcialSaleId { get; set; }
        public decimal FOutCommitQty { get; set; }
        public decimal FOutSecCommitQty { get; set; }
        public decimal FDBCommitQty { get; set; }
        public decimal FDBSecCommitQty { get; set; }
        public decimal FAuxQtyInvoice { get; set; }
        public int FOperSN { get; set; }
        public short FCheckStatus { get; set; }
        public Nullable<decimal> FSplitSecQty { get; set; }
        public int FInStockID { get; set; }
        public decimal FSaleCommitQty { get; set; }
        public decimal FSaleSecCommitQty { get; set; }
        public decimal FSaleAuxCommitQty { get; set; }
        public int FSelectedProcID { get; set; }
        public decimal FVWInStockQty { get; set; }
        public decimal FAuxVWInStockQty { get; set; }
        public decimal FSecVWInStockQty { get; set; }
        public decimal FSecInvoiceQty { get; set; }
        public int FCostCenterID { get; set; }
        public int FPlanMode { get; set; }
        public string FMTONo { get; set; }
        public Nullable<int> FRowClosed { get; set; }
        public Nullable<decimal> FDosage { get; set; }
    }
}
