//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.EMTModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_DY_MonldingGYLC
    {
        public int FID { get; set; }
        public int FClassTypeID { get; set; }
        public string FBillNo { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public int FClassGroup { get; set; }
        public int FClassType { get; set; }
        public int FJT { get; set; }
        public int FType { get; set; }
        public int FDept { get; set; }
        public string FGH { get; set; }
        public int FTS { get; set; }
        public decimal FWeight { get; set; }
        public string FFD { get; set; }
        public string FKZ { get; set; }
        public string FWD { get; set; }
        public string FJS { get; set; }
        public string FJJ { get; set; }
        public string FCW { get; set; }
        public string FQFD { get; set; }
        public string FQKZ { get; set; }
        public string FHKZ { get; set; }
        public string FText9 { get; set; }
        public int FCustermor { get; set; }
        public int FBL { get; set; }
        public string FColorNo { get; set; }
        public string FColorName { get; set; }
        public string FCPYQ { get; set; }
        public string FXJKZ { get; set; }
        public string FJB { get; set; }
        public string FCPKZ { get; set; }
        public string FQB { get; set; }
        public string FJSZ { get; set; }
        public string FJRY { get; set; }
        public string FAcross { get; set; }
        public string FStraight { get; set; }
        public string FTweak { get; set; }
        public string FJQB { get; set; }
        public string FNote { get; set; }
        public string FSZ { get; set; }
    }
}
