//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.EMTModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_DY_ColorNo
    {
        public int FID { get; set; }
        public int FClassTypeID { get; set; }
        public string FBillNo { get; set; }
        public int FBiller { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public int FChecker { get; set; }
        public Nullable<System.DateTime> FCheckDate { get; set; }
        public string FColorNo { get; set; }
        public int FColor { get; set; }
        public decimal FChroma { get; set; }
        public string FColorNoForCust { get; set; }
        public int FColorForCust { get; set; }
        public decimal FChromaForCust { get; set; }
        public int FColorNoType { get; set; }
        public int FCustID { get; set; }
        public int FItemID { get; set; }
        public string FColorName { get; set; }
        public int FShapi { get; set; }
        public string FColorNameForCust { get; set; }
        public string FProType { get; set; }
        public Nullable<decimal> FTotalAmount { get; set; }
        public Nullable<decimal> FTotalPlanAmount { get; set; }
    }
}
