//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.EMTModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_DY_RGStockBillEntry
    {
        public int FEntryID { get; set; }
        public int FID { get; set; }
        public int FIndex { get; set; }
        public Nullable<System.DateTime> FTime { get; set; }
        public string FGH { get; set; }
        public string FType { get; set; }
        public int FItemID { get; set; }
        public string FColorNo { get; set; }
        public string FColor { get; set; }
        public int FCustomer { get; set; }
        public int FQty { get; set; }
        public decimal FWeight { get; set; }
        public int FJT { get; set; }
        public int FZG { get; set; }
        public int FDS { get; set; }
        public string FBB { get; set; }
        public string FNote { get; set; }
        public int FDepartment { get; set; }
    }
}
