//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.EMTModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_DY_ColorNoEntry
    {
        public int FEntryID { get; set; }
        public int FID { get; set; }
        public int FIndex { get; set; }
        public int FMaterialID { get; set; }
        public int FItemType { get; set; }
        public int FWorkProcedure { get; set; }
        public decimal FDosage { get; set; }
        public string FGYTJ { get; set; }
        public string FGYH1 { get; set; }
        public string FGYH2 { get; set; }
        public string FNOTE { get; set; }
        public int FSB1 { get; set; }
        public int FSB2 { get; set; }
        public Nullable<decimal> FAmount { get; set; }
        public Nullable<decimal> FCB { get; set; }
        public Nullable<decimal> FPlanAmount { get; set; }
        public Nullable<decimal> FPlanCB { get; set; }
        public Nullable<decimal> FPlanPrice { get; set; }
        public Nullable<decimal> FPrice { get; set; }
    }
}
