//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.EMTModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Emp
    {
        public string FAddress { get; set; }
        public Nullable<decimal> FAllotPercent { get; set; }
        public string FBankAccount { get; set; }
        public Nullable<int> FBankID { get; set; }
        public Nullable<System.DateTime> FBirthday { get; set; }
        public string FBrNO { get; set; }
        public Nullable<decimal> FCreditAmount { get; set; }
        public Nullable<int> FCreditDays { get; set; }
        public Nullable<int> FCreditLevel { get; set; }
        public Nullable<int> FCreditPeriod { get; set; }
        public Nullable<int> FDegree { get; set; }
        public Nullable<short> FDeleted { get; set; }
        public Nullable<int> FDepartmentID { get; set; }
        public Nullable<int> FDuty { get; set; }
        public string FEmail { get; set; }
        public Nullable<int> FEmpGroup { get; set; }
        public Nullable<int> FEmpGroupID { get; set; }
        public Nullable<int> FGender { get; set; }
        public Nullable<System.DateTime> FHireDate { get; set; }
        public string FID { get; set; }
        public Nullable<bool> FIsCreditMgr { get; set; }
        public Nullable<int> FItemDepID { get; set; }
        public int FItemID { get; set; }
        public Nullable<int> FJobTypeID { get; set; }
        public Nullable<System.DateTime> FLeaveDate { get; set; }
        public string FMobilePhone { get; set; }
        public byte[] FModifyTime { get; set; }
        public string FName { get; set; }
        public string FNote { get; set; }
        public string FNumber { get; set; }
        public Nullable<int> FOperationGroup { get; set; }
        public Nullable<int> FOtherAPAcctID { get; set; }
        public Nullable<int> FOtherARAcctID { get; set; }
        public Nullable<int> FParentID { get; set; }
        public string FPhone { get; set; }
        public Nullable<int> FPreAPAcctID { get; set; }
        public Nullable<int> FPreARAcctID { get; set; }
        public Nullable<int> FProfessionalGroup { get; set; }
        public string FShortNumber { get; set; }
    }
}
