//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.EMTModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ICItemCore
    {
        public int FItemID { get; set; }
        public string FModel { get; set; }
        public string FName { get; set; }
        public string FHelpCode { get; set; }
        public Nullable<short> FDeleted { get; set; }
        public string FShortNumber { get; set; }
        public string FNumber { get; set; }
        public byte[] FModifyTime { get; set; }
        public Nullable<int> FParentID { get; set; }
        public string FBrNo { get; set; }
        public Nullable<int> FTopID { get; set; }
        public Nullable<short> FRP { get; set; }
        public Nullable<short> FOmortize { get; set; }
        public Nullable<short> FOmortizeScale { get; set; }
        public Nullable<bool> FForSale { get; set; }
        public Nullable<double> FStaCost { get; set; }
        public Nullable<double> FOrderPrice { get; set; }
        public Nullable<int> FOrderMethod { get; set; }
        public Nullable<int> FPriceFixingType { get; set; }
        public Nullable<int> FSalePriceFixingType { get; set; }
        public Nullable<double> FPerWastage { get; set; }
        public Nullable<int> FARAcctID { get; set; }
        public Nullable<short> FPlanPriceMethod { get; set; }
        public Nullable<short> FPlanClass { get; set; }
    }
}
