//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.EMTModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_MeasureUnit
    {
        public int FMeasureUnitID { get; set; }
        public int FUnitGroupID { get; set; }
        public string FNumber { get; set; }
        public string FAuxClass { get; set; }
        public string FName { get; set; }
        public Nullable<int> FConversation { get; set; }
        public decimal FCoefficient { get; set; }
        public int FPrecision { get; set; }
        public string FBrNo { get; set; }
        public int FItemID { get; set; }
        public Nullable<int> FParentID { get; set; }
        public short FDeleted { get; set; }
        public string FShortNumber { get; set; }
        public string FOperDate { get; set; }
        public decimal FScale { get; set; }
        public short FStandard { get; set; }
        public short FControl { get; set; }
        public byte[] FModifyTime { get; set; }
        public int FSystemType { get; set; }
        public System.Guid UUID { get; set; }
        public string FNameEN { get; set; }
        public string FNameEnPlu { get; set; }
    }
}
