//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.EMTModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Organization
    {
        public int FItemID { get; set; }
        public string FAddress { get; set; }
        public string FCity { get; set; }
        public string FProvince { get; set; }
        public string FCountry { get; set; }
        public string FPostalCode { get; set; }
        public string FPhone { get; set; }
        public string FFax { get; set; }
        public string FEmail { get; set; }
        public string FHomePage { get; set; }
        public string FCreditLimit { get; set; }
        public string FTaxID { get; set; }
        public string FBank { get; set; }
        public string FAccount { get; set; }
        public string FBankNumber { get; set; }
        public string FBrNo { get; set; }
        public Nullable<int> FBoundAttr { get; set; }
        public Nullable<int> FErpClsID { get; set; }
        public string FShortName { get; set; }
        public Nullable<int> FPriorityID { get; set; }
        public Nullable<int> FPOGroupID { get; set; }
        public Nullable<int> FStatus { get; set; }
        public Nullable<int> FLanguageID { get; set; }
        public Nullable<int> FRegionID { get; set; }
        public Nullable<int> FTrade { get; set; }
        public Nullable<double> FMinPOValue { get; set; }
        public Nullable<double> FMaxDebitDate { get; set; }
        public string FLegalPerson { get; set; }
        public string FContact { get; set; }
        public string FContactAcct { get; set; }
        public string FPhoneAcct { get; set; }
        public string FFaxAcct { get; set; }
        public string FZipAcct { get; set; }
        public string FEmailAcct { get; set; }
        public string FAddrAcct { get; set; }
        public Nullable<float> FTax { get; set; }
        public Nullable<int> FCyID { get; set; }
        public Nullable<int> FSetID { get; set; }
        public Nullable<int> FSetDLineID { get; set; }
        public string FTaxNum { get; set; }
        public Nullable<int> FPriceClsID { get; set; }
        public Nullable<int> FOperID { get; set; }
        public string FCIQNumber { get; set; }
        public short FDeleted { get; set; }
        public int FSaleMode { get; set; }
        public string FName { get; set; }
        public string FNumber { get; set; }
        public int FParentID { get; set; }
        public string FShortNumber { get; set; }
        public int FARAccountID { get; set; }
        public int FAPAccountID { get; set; }
        public int FpreAcctID { get; set; }
        public decimal FlastTradeAmount { get; set; }
        public decimal FlastRPAmount { get; set; }
        public string FfavorPolicy { get; set; }
        public int Fdepartment { get; set; }
        public int Femployee { get; set; }
        public string Fcorperate { get; set; }
        public Nullable<System.DateTime> FbeginTradeDate { get; set; }
        public Nullable<System.DateTime> FendTradeDate { get; set; }
        public Nullable<System.DateTime> FlastTradeDate { get; set; }
        public Nullable<System.DateTime> FlastReceiveDate { get; set; }
        public string FcashDiscount { get; set; }
        public int FcurrencyID { get; set; }
        public double FmaxDealAmount { get; set; }
        public double FminForeReceiveRate { get; set; }
        public double FminReserverate { get; set; }
        public int FdebtLevel { get; set; }
        public int FCarryingAOS { get; set; }
        public bool FIsCreditMgr { get; set; }
        public int FCreditPeriod { get; set; }
        public int FCreditLevel { get; set; }
        public int FPayTaxAcctID { get; set; }
        public Nullable<decimal> FValueAddRate { get; set; }
        public int FTypeID { get; set; }
        public Nullable<int> FCreditDays { get; set; }
        public Nullable<decimal> FCreditAmount { get; set; }
        public int FStockIDAssign { get; set; }
        public int FStockIDInst { get; set; }
        public Nullable<int> FStockIDKeep { get; set; }
        public Nullable<System.DateTime> FPaperPeriod { get; set; }
        public Nullable<int> FAlarmPeriod { get; set; }
        public bool FLicAndPermit { get; set; }
        public int FOtherARAcctID { get; set; }
        public int FOtherAPAcctID { get; set; }
        public int FPreAPAcctID { get; set; }
        public Nullable<int> FSaleID { get; set; }
        public string FHelpCode { get; set; }
        public byte[] FModifyTime { get; set; }
        public string FNameEN { get; set; }
        public string FAddrEn { get; set; }
        public string FCIQCode { get; set; }
        public Nullable<int> FRegion { get; set; }
        public string FMobilePhone { get; set; }
        public Nullable<int> FPayCondition { get; set; }
        public Nullable<int> FManageType { get; set; }
        public int FClass { get; set; }
        public string FValue { get; set; }
        public int FRegUserID { get; set; }
        public Nullable<System.DateTime> FLastModifyDate { get; set; }
        public Nullable<System.DateTime> FRecentContactDate { get; set; }
        public Nullable<System.DateTime> FRegDate { get; set; }
        public int FFlat { get; set; }
        public int FClassTypeID { get; set; }
    }
}
