//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.EMTModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_SubMessage
    {
        public string FBrNo { get; set; }
        public int FInterID { get; set; }
        public string FID { get; set; }
        public int FParentID { get; set; }
        public string FName { get; set; }
        public Nullable<short> FTypeID { get; set; }
        public short FDetail { get; set; }
        public short FDeleted { get; set; }
        public byte[] FModifyTime { get; set; }
        public int FSystemType { get; set; }
        public string FSpec { get; set; }
        public System.Guid UUID { get; set; }
    }
}
