//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.EMTModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_DYJXC_YZKTrack
    {
        public string FGH { get; set; }
        public int FWorkProcedure { get; set; }
        public int FIndex { get; set; }
        public string FName { get; set; }
        public Nullable<decimal> FNum { get; set; }
        public Nullable<System.DateTime> FRecDate { get; set; }
        public string FOperType { get; set; }
    }
}
