//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.DYModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DYContainer : DbContext
    {
        public DYContainer()
            : base("name=DYContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ControllerActionRoleSet> ControllerActionRoleSet { get; set; }
        public virtual DbSet<ControllerActionSet> ControllerActionSet { get; set; }
        public virtual DbSet<t_RoleSet> t_RoleSet { get; set; }
        public virtual DbSet<t_UserRoleSet> t_UserRoleSet { get; set; }
        public virtual DbSet<t_Users> t_Users { get; set; }
        public virtual DbSet<t_DYJXC_GXHB> t_DYJXC_GXHB { get; set; }
        public virtual DbSet<t_HK_PGData> t_HK_PGData { get; set; }
        public virtual DbSet<t_Material> t_Material { get; set; }
    }
}
