//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.DYModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_DYJXC_TestData
    {
        public string lot { get; set; }
        public string kf { get; set; }
        public string bn { get; set; }
        public string cn { get; set; }
        public string qc { get; set; }
        public string rb { get; set; }
        public string fca { get; set; }
        public string fco { get; set; }
        public string fpa { get; set; }
        public string fpe { get; set; }
        public string fpc { get; set; }
        public string fwo { get; set; }
        public string fcc { get; set; }
        public string sca { get; set; }
        public string sco { get; set; }
        public string spa { get; set; }
        public string spe { get; set; }
        public string spc { get; set; }
        public string swo { get; set; }
        public string scc { get; set; }
        public string tca { get; set; }
        public string tco { get; set; }
        public string tpa { get; set; }
        public string tpe { get; set; }
        public string tpc { get; set; }
        public string two { get; set; }
        public string tcc { get; set; }
        public string cica { get; set; }
        public string cico { get; set; }
        public string cipa { get; set; }
        public string cipe { get; set; }
        public string cipc { get; set; }
        public string ciwo { get; set; }
        public string cicc { get; set; }
        public string alca { get; set; }
        public string alco { get; set; }
        public string alpa { get; set; }
        public string alpe { get; set; }
        public string alpc { get; set; }
        public string alwo { get; set; }
        public string alcc { get; set; }
        public string wca { get; set; }
        public string wco { get; set; }
        public string wpa { get; set; }
        public string wpe { get; set; }
        public string wpc { get; set; }
        public string wwo { get; set; }
        public string wcc { get; set; }
        public string efca { get; set; }
        public string efco { get; set; }
        public string efpa { get; set; }
        public string efpe { get; set; }
        public string efpc { get; set; }
        public string efwo { get; set; }
        public string efcc { get; set; }
        public string esca { get; set; }
        public string esco { get; set; }
        public string espa { get; set; }
        public string espe { get; set; }
        public string espc { get; set; }
        public string eswo { get; set; }
        public string escc { get; set; }
        public string fc { get; set; }
        public string sc { get; set; }
        public string dr { get; set; }
        public string wet { get; set; }
        public string ph { get; set; }
        public string li { get; set; }
        public string lx { get; set; }
        public string we { get; set; }
        public string le { get; set; }
        public string wre { get; set; }
        public string lre { get; set; }
        public string pil { get; set; }
        public string tn { get; set; }
        public string wl { get; set; }
        public string l { get; set; }
        public string g { get; set; }
        public string wg { get; set; }
        public string cu { get; set; }
        public string bur { get; set; }
        public string tfw { get; set; }
        public string tfl { get; set; }
        public string sw { get; set; }
        public string sl { get; set; }
        public string fn { get; set; }
        public string sn { get; set; }
        public string wk { get; set; }
        public string tda { get; set; }
        public string tm { get; set; }
        public string thno { get; set; }
        public string tno { get; set; }
        public string drt { get; set; }
        public string fd { get; set; }
        public string pl { get; set; }
        public string pg { get; set; }
        public string meo { get; set; }
        public string sm { get; set; }
        public string fl { get; set; }
        public string fw { get; set; }
        public string n { get; set; }
        public string ppm { get; set; }
        public string pkg { get; set; }
        public string ts { get; set; }
        public string cy { get; set; }
        public string wk1 { get; set; }
        public string ll { get; set; }
        public string ff { get; set; }
        public string rbl { get; set; }
        public string pp { get; set; }
        public string kslca { get; set; }
        public string kslco { get; set; }
        public string kslpa { get; set; }
        public string kslpe { get; set; }
        public string kslpc { get; set; }
        public string kslwo { get; set; }
        public string kslcc { get; set; }
        public string ksca { get; set; }
        public string ksco { get; set; }
        public string kspa { get; set; }
        public string kspe { get; set; }
        public string kspc { get; set; }
        public string kswo { get; set; }
        public string kscc { get; set; }
        public string wlpg { get; set; }
        public string gpg { get; set; }
    }
}
