//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.DYModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Material
    {
        public int FItemID { get; set; }
        public string FNumber { get; set; }
        public string FModel { get; set; }
        public string FName { get; set; }
        public Nullable<int> FUnitID { get; set; }
        public string FUnitName { get; set; }
        public string FAlias { get; set; }
        public Nullable<short> FDeleted { get; set; }
        public Nullable<int> FParentID { get; set; }
        public string FShortNumber { get; set; }
        public Nullable<decimal> FKFPeriod { get; set; }
    }
}
