//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.DYModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Users
    {
        public string FUserCode { get; set; }
        public string FUserName { get; set; }
        public string FGroupCode { get; set; }
        public string FPassWord { get; set; }
        public Nullable<bool> FEnable { get; set; }
        public Nullable<int> FDeptCode { get; set; }
        public string FMemo { get; set; }
        public string FCompany { get; set; }
        public string FCreator { get; set; }
        public Nullable<System.DateTime> FCreateDate { get; set; }
        public string FModMan { get; set; }
        public Nullable<System.DateTime> FModDate { get; set; }
        public string UDF01 { get; set; }
        public string UDF02 { get; set; }
        public string UDF03 { get; set; }
        public string UDF04 { get; set; }
        public string UDF05 { get; set; }
    }
}
