//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.DYModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_DeliveryTrack
    {
        public string FGH { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string OrgName { get; set; }
        public string ItemName { get; set; }
        public string ItemModel { get; set; }
        public Nullable<System.DateTime> DXPlan { get; set; }
        public Nullable<System.DateTime> DXReality { get; set; }
        public Nullable<System.DateTime> YDPlan { get; set; }
        public Nullable<System.DateTime> YDReality { get; set; }
        public Nullable<System.DateTime> RSPlan { get; set; }
        public Nullable<System.DateTime> RSReality { get; set; }
        public Nullable<System.DateTime> RCPlan { get; set; }
        public Nullable<System.DateTime> RCReality { get; set; }
        public Nullable<decimal> DXOutDays { get; set; }
        public Nullable<decimal> YDOutDays { get; set; }
        public Nullable<decimal> RSOutDays { get; set; }
        public Nullable<decimal> RCOutDays { get; set; }
    }
}
