//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.DYModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_YzkRS
    {
        public string 缸号 { get; set; }
        public Nullable<System.DateTime> 开卡日期 { get; set; }
        public string 客户名称 { get; set; }
        public Nullable<decimal> 胚重 { get; set; }
        public Nullable<int> 条数 { get; set; }
        public Nullable<decimal> 实重 { get; set; }
        public Nullable<decimal> 净重 { get; set; }
        public Nullable<decimal> 染损 { get; set; }
    }
}
